services:
  - type: web
    name: lightmusic-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2
    envVars:
      - key: YT_COOKIES
        sync: false